#!/usr/bin/env bash
source ~/environment.tmp
export $(cut -d= -f1 ~/environment.tmp)
exe="/Applications/Toon Boom Harmony 17 Premium/Harmony Premium.app/Contents/MacOS/Harmony Premium"
/usr/local/pype/pype_env2/bin/python3 -c "import avalon.harmony;avalon.harmony.launch('$exe')"
