
version_padding: 3
version: "v{version:0>{@version_padding}}"
frame_padding: 4
udim_padding: 4
frame: "{frame:0>{@frame_padding}}"
udim: "{udim:0>{@udim_padding}}"

work:
  folder: "{root}/{project[name]}/{hierarchy}/{asset}/work/{task}"
  file: "{project[code]}_{asset}_{task}_{@version}<_{comment}>.{ext}"
  path: "{@folder}/{@file}"

render:
  folder: "{root}/{project[name]}/{hierarchy}/{asset}/publish/render/{subset}/{@version}"
  file: "{project[code]}_{asset}_{subset}_{@version}<_{output}><.{@frame}>.{representation}"
  path: "{@folder}/{@file}"

texture:
  path: "{root}/{project[name]}/{hierarchy}/{asset}/publish/{family}/{subset}"

publish:
  folder: "{root}/{project[name]}/{hierarchy}/{asset}/publish/{family}/{subset}/{@version}"
  file: "{project[code]}_{asset}_{subset}_{@version}<_{output}><.{@frame}><_{@udim}>.{representation}"
  path: "{@folder}/{@file}"
  thumbnail: "{thumbnail_root}/{project[name]}/{_id}_{thumbnail_type}{ext}"

master:
  folder: "{root}/{project[name]}/{hierarchy}/{asset}/publish/{family}/{subset}/master"
  file: "{project[code]}_{asset}_{subset}_master<_{output}><.{@frame}>.{representation}"
  path: "{@folder}/{@file}"
